version: "3.9"

name: "djn"
services:
    app.djn.io:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/djnapp
        environment:
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        env_file:
            - ./secrets/djn.env
        ports:
            - 8000:8000
        expose:
            - 8000
        depends_on:
            - db.postgres.io
            - cache.redis.io

    auth.keycloak.io:
        image: jboss/keycloak
        restart: unless-stopped
        command:
            - "-Dkeycloak.profile.feature.upload_scripts=enabled"
        env_file:
            - ./secrets/keycloak.env
        environment:
            JDBC_PARAMS: "useSSL=false"
            PROXY_ADDRESS_FORWARDING: "false"
        depends_on:
            - keycloak.postgres.io
        ports:
            - 8088:8080
        expose:
          - 8088

    cache.redis.io:
        image: "redis:alpine"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 30s
            retries: 3

    db.postgres.io:
        image: postgres:13
        restart: unless-stopped
        env_file:
            - ./secrets/db.env
        command: postgres -c 'max_connections=${PG_MAX_CONNECTIONS}'
        volumes:
            - postgres_db:/var/lib/postgresql/data

    keycloak.postgres.io:
        image: postgres:13
        restart: unless-stopped
        volumes:
            - keycloak_postgres_data:/var/lib/postgresql/data
        env_file:
           - ./secrets/kdb.env
        healthcheck:
            test: "exit 0"
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    postgres_db: {}
    keycloak_postgres_data:
        driver: local
